### PR TITLE
Add a getting started notebook MERGEOK

### PR DESCRIPTION
**Pull request by kkraune**
- This is based on feed-query-and-other-document-operations.ipynb
- I want to replace feed-query-and-other-document-operations.ipynb with this, as it is a more complete example, and imho a good place to start to try out pyvespa in full
- This guide resembles the other vespa quickstart guides, configure, feed, query

### CODE REVIEW

**Review by jobergum — APPROVED** [review]

**Comment by jobergum** [comment]
Could you add a step that exports the generated application package?

**Comment by kkraune** [comment]
agreed JKB. I'll merge this while exploring pyvespa for export - any help appreciated, @thigm85

**Comment by thigm85** [comment]
The application package files are exported to disk when deploying to Docker. Is this the desired behavior @jobergum mention?

**Comment by kkraune** [comment]
yes @thigm85 (thanks for helping!) - I added this in https://github.com/vespa-engine/pyvespa/pull/265

**Pull request merged**
