### PR TITLE
Use expression { <expr> } instead of expression: <expr> MERGEOK

### PR DESCRIPTION
**Pull request by maxice8**
Allows handling more complex functions

### CODE REVIEW

**Comment by maxice8** [comment]
Updated to last

**Comment by maxice8** [comment]
synced with d5ecdc26605713ca6a83dd11daee84fe44f6dd14

**Comment by maxice8** [comment]
synced to f309880

**Comment by maxice8** [comment]
synced with 8d644fee7d55127c096dfe412c43a680754e4548

**Review by lesters — APPROVED** [review]

**Pull request merged**
