### PR TITLE
Demonstrate that hamming MaxSim is a very good alternative to float based MaxSim 

### PR DESCRIPTION
**Pull request by jobergum**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by thomasht86** [comment]
Seems like a very attractive tradeoff! 💯 
Would be nice if you could use a recent notebook as basis (without all the CLI-commands and auth-stuff that we now no longer need.) And Colab-badge. :)

**Comment by thomasht86** [comment]
See that CI fail due to missing PIL - `pip install pillow`

**Comment by jobergum** [comment]
Will do! One issue here with having this in CD is that it takes 20 minutes to encode the corpus, but let us see first how long it takes, and then maybe run it once in a while or something.

**Comment by thomasht86** [comment]
Looks like we're not able to run this in CI without larger runners. 
Crashes in Colab as well with the standard CPU runtime (works with T4 though).
I'll follow up on getting us access to larger runners, but we'll probably need to exclude it for now.

**Comment by jobergum** [comment]
Yeah, as the model is 12GB and it encodes the images + overhead I do imagine we pass the runner memory limits. I would like to keep this notebook though so if you could disable it from test for now that would be great. Thanks!

**Review by thomasht86 — APPROVED** [review]
👍

**Pull request merged**
