### PR TITLE
Add ability to update with create

### PR DESCRIPTION
**Pull request by ausnews**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by thigm85** [comment]
@ausnews Thanks for contributing. I will take a look.

**Review by thigm85 — APPROVED** [review]
I added two integration tests, one for docker and another for cloud deployment.

**Comment by ausnews** [comment]
Thank you! Apologies for the test laziness.

**Comment by thigm85** [comment]
No problem. Future contributions are welcome.

**Pull request merged**
