### PR TITLE
Add paragraph indexing MERGEOK

### PR DESCRIPTION
**Pull request by kkraune**

### CODE REVIEW

**Review by jobergum — APPROVED** [review]

**Review by jobergum — CHANGES_REQUESTED** [review]
Missing markdownify dependency

**Comment by kkraune** [comment]
not sure I understand, we got
```
pip3 install PyYAML spacy mmh3 requests html5lib beautifulsoup4 markdownify tiktoken
```

**Review by jobergum — APPROVED** [review]

**Comment by jobergum** [comment]
Something with the PR build then :)

**Comment by kkraune** [comment]
the doctest step runs all python files - it should not run the new files added here, will add an ignore

**Pull request merged**
