### PR TITLE
Exclude test files from the package

### PR DESCRIPTION
**Pull request by rejasupotaro**
## Overview

When writing code, I noticed that the `vespa` package has modules for its testing.

Screenshot 2024-01-09 at 7 48 46

Following the common practice, I moved test files to the `tests` directory not to include them in the package.

While this PR does not alter the tests themselves, it does modify the project's structure ⚠️ However, as the project management style is up to the owner, feel free to close this PR if this approach is not preferable.

## Files in Package

Python includes all files in a directory as part of the package. We can see what files are included by unzipping the built package.

<details>

<summary>Before</summary>

```
$ python -m build
$ cd dist
$ unzip pyvespa-0.7.0+dev-py3-none-any.whl
$ tree vespa
vespa
├── __init__.py
├── application.py
├── deployment.py
├── exceptions.py
├── io.py
├── package.py
├── py.typed
├── templates
│   ├── hosts.xml
│   ├── macros.txt
│   ├── query_profile.xml
│   ├── query_profile_type.xml
│   ├── schema.txt
│   ├── services.xml
│   └── validation-overrides.xml
├── test_application.py
├── test_integration_docker.py
├── test_integration_vespa_cloud.py
├── test_integration_vespa_cloud_token.py
├── test_integration_vespa_cloud_vector_search.py
├── test_io.py
└── test_package.py

1 directory, 21 files
```

</details>

If we have the `tests` directory, test files are now not included in the package as shown below.

<details>

<summary>After</summary>

```
$ python -m build
...
$ tree vespa
vespa
├── __init__.py
├── application.py
├── deployment.py
├── exceptions.py
├── io.py
├── package.py
├── py.typed
└── templates
    ├── hosts.xml
    ├── macros.txt
    ├── query_profile.xml
    ├── query_profile_type.xml
    ├── schema.txt
    ├── services.xml
    └── validation-overrides.xml
```

</details>

Other than this, it is convenient if we have a separate directory for tests when adding more tests using fixtures https://docs.pytest.org/en/6.2.x/fixture.html.

## Dependency Management

Apart from the main topic of this PR, I encountered the following error while writing tests for another PR.

```
(.venv) ~/p/pyvespa ❯❯❯ pytest
=========================================================================================================== test session starts ============================================================================================================
platform darwin -- Python 3.8.15, pytest-7.2.2, pluggy-1.0.0
rootdir: /Users/kentaro-takiguchi/projects/pyvespa
collected 74 items / 1 error

================================================================================================================== ERRORS ==================================================================================================================
________________________________________________________________________________________________ ERROR collecting vespa/test_application.py ________________________________________________________________________________________________
ImportError while importing test module '/Users/kentaro-takiguchi/projects/pyvespa/vespa/test_application.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../.pyenv/versions/3.8.15/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
vespa/test_application.py:14: in <module>
    import requests_mock
E   ModuleNotFoundError: No module named 'requests_mock'
========================================================================================================= short test summary info ==========================================================================================================
ERROR vespa/test_application.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================================================= 1 error in 1.90s =============================================================================================================
```

I read `screwdriver.yaml` and found that extra dependencies were added in place. It would be ideal to manage such dependencies in `setup.py` like https://github.com/raphaelsty/neural-cherche/blob/main/setup.py#L42

```
+    extras_require={
+        "dev": [
+            "pytest",
+            "requests-mock",
+            "datasets",
+            "notebook",
+            "nbconvert",
+            "runnb",
+        ],
+    },
```

---

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by jobergum — APPROVED** [review]

**Comment by jobergum** [comment]
Wonderful! Thank you

**Comment by rejasupotaro** [comment]
@jobergum Thank you for your review!

I saw that @tmaregge modified a test file in https://github.com/vespa-engine/pyvespa/pull/656. It's fine for me to update this branch after his PR is merged, and it's also okay to merge this PR first. Either way, since this PR does not change the test files themselves, resolving any conflicts should be straightforward.

**Comment by jobergum** [comment]
Thank you, just merged https://github.com/vespa-engine/pyvespa/pull/656 so would deeply appreciate that. Thank you for your very valuable contributions to pyvespa!

**Comment by rejasupotaro** [comment]
I've merged the master branch into this branch.

It appears that CI failed on the main branch https://cd.screwdriver.cd/pipelines/7055/builds/917676/steps/run-notebooks-cloud-related after his PR was merged but passed on this branch. I guess this is due to some randomness in CI 🤔

**Review by jobergum — APPROVED** [review]

**Comment by jobergum** [comment]
Will look into the llama_index notebook, about time to get all the recent features into a release

**Comment by jobergum** [comment]
And thank you again for your valuable contributions @rejasupotaro !

**Pull request merged**
