### PR TITLE
Kkraune/misc

### PR DESCRIPTION
**Pull request by kkraune**
- no functional changes, just renames / cleanup for less warnings

### CODE REVIEW

**Comment by kkraune** [comment]
@freva please review - should be no functional changes except for the contant -> constant typo, the correction is correct per @thigm85 (who is on PTO these days). This is just cleaning up warnings in the IDE

**Review by freva — COMMENTED** [review]
Some methods are changed to static, but their are still invoked via `self`...

**Comment by thigm85** [comment]
@kkraune I will be able to review this today as well.

**Review by thigm85 — APPROVED** [review]

**Review by freva — COMMENTED** [review]
I think you also need to update `return model.parse_vespa_prediction(` in `vespa/application.py` to `TextTask.parse_vespa_prediction(` (Ref static method change in `vespa/ml.py`)

**Comment by kkraune** [comment]
> model.parse_vespa_prediction

you are right! thanks

**Review by freva — APPROVED** [review]

**Pull request merged**
