### PR TITLE
Add new colpali example

### PR DESCRIPTION
**Pull request by jobergum**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by jobergum** [comment]
Input welcome on this, both language and code, also would be nice to see if we can get this into CI/CD

**Comment by thomasht86** [comment]
Very cool! 🤩
Was able to run it on Colab ✅

Some comments:
- Making it run on CI
As a start, we could add
```bash
!sudo apt-get install poppler-utils -y
``` 
Should also move the note about poppler dependency there, and maybe link to other [install options. ](https://pdf2image.readthedocs.io/en/latest/installation.html).
But, it will most likely take prohibitively long to run this on CPU. Possible to scale down number of docs/images to a minimum if running on CPU?

- The cell below
image

Takes  1.5*15=22.5 mins to run in Colab with A100 GPU. 🐌
(Didn't bother to wait with T4.) Perhaps add a note about that. ☕

- Could be nice to add [Open In Colab](https://colab.research.google.com/github/vespa-engine/pyvespa/blob/master/docs/sphinx/source/examples/simplified-retrieval-with-colpali-vlm_Vespa-cloud.ipynb) to the top (I did this for the other cloud nbs in the big batch update)

- The cell below 
Screenshot 2024-09-06 at 17 24 57

Causes linting error in Colab (and older versions of eg. [pylance](https://github.com/microsoft/pylance-release/issues/3205) Consider using https://pyvespa.readthedocs.io/en/latest/reference-api.html#vespa.application.Vespa.feed_async_iterable for feeding at least. 

- `tenant_name = "samples"` would need to change to `vespa-team` to run in CI.

**Comment by jobergum** [comment]
Great, thanks for this! Will iterate

> Takes 1.5*15=22.5 mins to run in Colab with A100 GPU. 

This is super weird as it takes just 12-15 seconds per batch on my M1 with MPS

**Comment by thomasht86** [comment]
Looks like the latest run encountered [this hf issue](https://github.com/huggingface/datasets/issues/7141)

**Comment by thomasht86** [comment]
Great. Ran successfully in 25mins - we can add it to CI. 👍 
(Wonder what my issue on Colab was though).

Consider less printout of b64-strings and embeddings (will force the reader to scroll a lot).

**Comment by thomasht86** [comment]
Made this for my own understanding.
May be useful for others. 😄 
Feel free to add (or dm if you want to modify).

Phased ranking Colpali

**Comment by jobergum** [comment]
It's a good overview diagram! Removed the larger output and also looks like cd passed

**Review by thomasht86 — APPROVED** [review]
🙌

**Pull request merged**
