### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by kkraune**

### CODE REVIEW

**Comment by kkraune** [comment]
work note:
```
find . -name \*.py -or -name \*.ipynb | xargs sed -i.orig "s/is_successfull()/is_successful()/g"
find . -name \*.orig | xargs rm
```

**Comment by jobergum** [comment]
For this we also need to change vespa.io.VespaResponse.is_successfull - I suggest that we unbreak this by adding a new method and deprecate the misspelled variant?

**Comment by kkraune** [comment]
right, will update PR

**Comment by kkraune** [comment]
the regexp did of course not catch `is_successfull(self)` - adding now

**Review by jobergum — APPROVED** [review]

**Pull request merged**
