### PR TITLE
Allow to specify mutate operation in RankProfile

### PR DESCRIPTION
**Pull request by Fed0rah**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by thomasht86** [comment]
Thanks a lot for your contribution @Fed0rah! 🙏 
This would be very nice!
See requested change. 

I would also love to see a unit test with a schema that makes use of this. 
See e.g https://github.com/vespa-engine/pyvespa/blob/30f9aba53d7a7f11af02e6d500d02143077b1139/tests/unit/test_package.py#L184 for a template to modify from.

**Comment by Fed0rah** [comment]
Thank you for your quick feedback !
Would something like this do the work ?

**Comment by bratseth** [comment]
Great contribution @Fed0rah. I'm curious if you are using this beyond expert-level feature?

**Comment by bratseth** [comment]
Cool, you should do a blog on it, we'll be happy to host/co-host it.

**Review by thomasht86 — APPROVED** [review]
Thank you for a superb contribution! 🥇 
We would really love to learn more about your Vespa usage.

Have you joined our [slack workspace](https://join.slack.com/t/vespatalk/shared_invite/zt-nq61o73o-Lsun7Fnm5N8uA6UAfIycIg)?

**Pull request merged**
