### PR TITLE
Make it easier to use existing tenant/app/instance

### PR DESCRIPTION
**Pull request by kkraune**

### CODE REVIEW

**Review by thigm85 — APPROVED** [review]
LGTM

**Comment by thigm85** [comment]
@kkraune The link checker is running the notebook because none of the cells have been run by you, and the notebook is not executable without user intervention. So I suggest you run at least some of the cells and save the notebook. The link checker assumes the notebook was already run and skips this step.

**Review by thigm85 — CHANGES_REQUESTED** [review]
Run at least one notebook cell to avoid it being run by the link-checker.

**Comment by kkraune** [comment]
Thanks! I did not know about the link checker / run cells. will this do?

**Review by thigm85 — APPROVED** [review]
Thanks

**Pull request merged**
